/// Flutter icons BsrIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BsrIcons
///      fonts:
///       - asset: fonts/BsrIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BsrIcons {
  BsrIcons._();

  static const _kFontFam = 'BsrIcons';
  static const String? _kFontPkg = null;

  static const IconData packaging = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biologicalWaste = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData residualWaste = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperWaste = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
